
import Head from "next/head";
import Link from "next/link";


export default function Home() {
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="flex items-center space-x-2">
        
        </div>
        

      </main>
    </>
  );
}
